# Generated by Django 2.0.2 on 2018-02-16 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholConsumptionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
                ('alcohol_amount', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Amount of alcohol in % ')),
                ('liquid_amount', models.IntegerField(verbose_name='Amount of liquid (ml)')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
                ('drink_class', models.IntegerField(choices=[(2, 'Liquor'), (1, 'Soft alcholic drink'), (0, 'Alcohol free'), (4, 'Mixed drink'), (3, 'Hard liquor')], verbose_name='Drink class')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('party_date', models.DateTimeField(verbose_name='Date of the party')),
                ('party_end', models.DateTimeField(verbose_name='Date of the party termination')),
            ],
        ),
        migrations.CreateModel(
            name='LiveSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_default_event', models.ForeignKey(blank=True, help_text='Sets current event to new accounts', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BeerTracker.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patrons', to='BeerTracker.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeerTracker.Venue'),
        ),
        migrations.AddField(
            model_name='drink',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeerTracker.DrinkType'),
        ),
        migrations.AddField(
            model_name='alcoholconsumptionevent',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeerTracker.Drink'),
        ),
        migrations.AddField(
            model_name='alcoholconsumptionevent',
            name='drinker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='BeerTracker.Patron'),
        ),
        migrations.AddField(
            model_name='alcoholconsumptionevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeerTracker.Event'),
        ),
    ]
