# Generated by Django 2.0.2 on 2018-02-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinktype',
            name='drink_class',
            field=models.IntegerField(choices=[(0, 'Alcohol free - ~0%'), (1, 'Soft alcholic beverage - <9%'), (2, 'Strong alcoholic beverage - 9%-22%'), (3, 'Liquor - 20%-50%'), (4, 'Strong liquor - >50%'), (5, 'Mixed drink - Any ABV')], verbose_name='Drink class'),
        ),
    ]
